### ISSUE TITLE
Add analysis screen to workspace

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/varify#169] opened 2014-03-13 16:24 UTC
As discussed in our meeting, we should add a panel for analysis underneath the existing saved and shared query panels. This would allow users to jump right to an analysis view showing sets of variants categorized by knowledge capture.

**Comment by naegelyd** [comment] 2014-04-15 19:43
The work on this issue has significant overlap with #170. Considering this, I'm closing this as a duplicate of #170 and all the analysis work can reference that issue.

**Closed as completed by naegelyd** 2014-04-15 19:43 UTC
Labels: type:feature, version 0.1
