### ISSUE TITLE
Proposal for a revised schema: more efficient and consistent internal storage of ref/alt sequences

### ISSUE THREAD

**Issue by awenocur** [chop-dbhi/varify#305] opened 2014-05-21 17:05 UTC
I'm in the process of adding/removing a couple models, and revising others: Result, Variant.  Model declarations are to follow.

**Comment by bruth** [comment] 2014-05-21 17:33
Can you please explain what you intend to do? Obviously there are a lot of ramifications to changing the data model. If what you propose is valid, then each data model change should be broken up into separate tickets since they may require many changes over the codebase.

In addition, since this appears to be driven by the need for storage efficiency or performance, please supply benchmarks comparing the current data model with the new one.

**Comment by penningtonj** [comment] 2014-05-21 17:38
Hi Adam, what progress have you made on the API? How do these proposed changes contribute to a functional API?  The Varify schema is quite stable and performant for existing applications, so I am wary of spending time on it instead of more urgent issues.

**Comment by leipzig** [comment] 2014-05-21 17:43
This kind of started because the API demands Varify know how to export calls from samples that were processed in different runs. Unfortunately we were so faithful to the VCF notations of 0's for reference and 1/2/etc... for whatever alternates were observed that makes it difficult to reconcile these calls. However I think Adam can ignite some schema discussion here and we can continue to move forward on the API.

**Comment by mitalia** [comment] 2014-05-21 17:48
I would also comment that there have been a lot of discussions at different points in time about how best to revise the data model over time. There are things we don't have in there at all (e.g. reference calls) that need to be there. There are also some things that probably need to genuinely be changed  (e.g some of the stuff we inherit from VCF is not desirable as @leipzig points out).

I think before entertaining major schema changes, we would do well to increase our test coverage for major data models and loaders. I am loathe to make changes with huge ramifications in the absence of any way to verify new behavior is the same as existing behavior.

**Comment by naegelyd** [comment] 2014-05-21 17:59
Like the other commenters, I am extremely hesitant to make any changes to
the core data models(Sample, Result, Variant) until the tests are much
improved and the changes are adequately evaluated here and have benchmarks
showing that they, at a minimum, don't hurt the performance. In my opinion,
the loader would be a much better area to target for a performance
boost/refractor. As others have said, the data model is stable and changes
to it could have incredible consequences so any changes need to be
thoroughly vetted before they are introduced in to varify.

**Comment by awenocur** [comment] 2014-05-21 18:15
I was planning on adding issues for each detail, however there are several ways in which the existing schema is more a representation of the VCF format itself rather than the data gleaned therefrom.  Ideally, we should not have to parse text out of query results, do string comparisons outside the DBMS, or make inferences about missing data for a simple exporter.  Thus far, all of these would be necessary if I were to complete the exporter using the extant schema.

**Comment by bruth** [comment] 2014-05-21 18:25
Can you list the data elements that require a refactoring to continue discussion? We need to be wary of data model changes that provide an optimization for one use case. I am not suggesting that the current data model is optimal, but it has worked thus far and we've learned how to optimize it.

On a side note, what exactly can't you reproduce in the VCF export given that the loaded data derived from VCF files?

**Comment by awenocur** [comment] 2014-05-21 18:31
My primary concern is with the ref/alt alleles and the way they're represented as @leipzig commented above.  The numbering scheme used in the VCF format serves no purpose in a database driven app, shouldn't be a text field, and actually limits the ways in which variants can be referenced across samples.

**Comment by leipzig** [comment] 2014-05-21 18:39
OK I think part of this (not the reference intervals part) can be dealt with more work on the loaders. So an entry like this in the variant table will be difficult to pull apart in real-time. Perhaps the loader should put in two variant entries here so that no individual gets a call like 0/2.

```
id   chr_id   pos   ref   alt   md5   rsid   type_id   liftover   gene_id
3088581   14   104177190   AAC   A,AACACACACAC   e891778aea82021b3885eaa3f185fe32   rs139961690   2     
```

**Comment by bruth** [comment] 2014-05-21 18:52
Splitting the alt allele is a good change. That should have a pretty minimal impact across the board. I recommend creating two separate _new_ columns, updating the loader, and changing `alt` into an instance property that concatenates the two new values to preserve the original format. In theory this should not result in a breaking change for the APIs that consume the `alt` value.

**Comment by awenocur** [comment] 2014-05-21 19:00
This would be a good first step toward adapting the schema.  Perhaps a similar cycle of adding columns prior to replacement could slowly nudge the Variant table toward being capable of accommodating intervals.

I'm looking into the idea of implementing new ref/alt columns.  If they could be foreign keys, the loader could be modified to create a table of all unique variants and reference them rather than relying on the VCF convention.

**Comment by bruth** [comment] 2014-05-21 19:09
The variant table already enforces uniqueness. The sample result table is a "sample-specific variant" between sample and variant.

**Comment by awenocur** [comment] 2014-05-21 19:10
Right, @bruth; the term "variant" is ambiguous here.  I was referring to the verbatim nucleotide sequence, not tuples in the Variant table.

**Comment by bruth** [comment] 2014-05-21 19:20
I do not think it is ambiguous at all. Unique variants are handled already. What you are suggesting is a separate table of unique nucleotide sequences.

**Comment by awenocur** [comment] 2014-05-21 19:33
That's the problem here; the client code must make string comparisons among results from the Variant table under certain circumstances to resolve the numbering notation inherited from the VCF import, across runs. While uniqueness is enforced on tuples in the variant table, a given variant can be stored in different ways depending on the run.

The ref/alt fields aren't even faithful to reference and alternate sequences.  For Het Alt variants, the Ref field represents allele 1 of a given run.

**Comment by naegelyd** [comment] 2014-07-02 20:07
Closing this as the discussion seems to have run its course. Any specific items that need to be worked on as identified by the above discussion can be filed as separate issues.

**Closed as completed by naegelyd** 2014-07-02 20:07 UTC
